# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inspired-Sec
email: jcatrambone@inspired-sec.com
description: Penetration Testing tips and tricks that will hopefully make your struggles at least a little bit better :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.inspired-sec.com" # the base hostname & protocol for your site
twitter_username: n0pe_sled
github_username:  jcatrambone94
paginate: 5

gems: [jekyll-paginate, kramdown, jekyll-redirect-from]
# Build settings
markdown: kramdown
google_analytics: UA-93958329-1
